version: '3.7'
services:
  db_stackunderflow:
    image: mysql
    container_name: db_stackunderflow
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: amt_stackunderflow
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    expose:
      - '3306'
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d

  webapp_stackunderflow:
    image: amt/stackunderflow
    container_name: webapp_stackunderflow
    environment:
     - ADMIN_PASSWORD=admin #TODO choisir un mdp simple mais différent
    ports:
     - "8080:8080"
     - "8443:8443"

